### ISSUE TITLE
Temporary File Created

### ISSUE THREAD

**Issue by iguarin** [senecaifs/c3x-2018-ticketing#6]
## Abstract

Processname: Microsoft.Tri.Gateway.exe
Host: wec01
Temp directory: @"C:\Windows\ServiceProfiles\LocalService\AppData\Local\Temp\gcturrvv.cmdline"

## Operations needed

Track the logs that may be related to the process name.

## Detailed Description

Fill in a detailed technical description here.

**Comment by laksman11** [comment]
Investigation complete, hash ran through VT safe
